name: healt
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  record: 4.4.4
  path_provider: ^2.1.2

  http: ^1.2.1
  file_picker: ^8.0.0
  image_picker: ^1.0.7

  google_mlkit_text_recognition: ^0.13.0

  # ðŸ”Š Voice
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.5

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4

  firebase_core: ^2.30.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1

  # âœ¨ Animations (REQUIRED for Home UI)
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  web: ^0.5.1

flutter:
  uses-material-design: true
